export const S = {
  page:         { minHeight: '100vh', background: '#f1f5f9', padding: '20px 16px 12px' },
  container:    { maxWidth: 1100, margin: '0 auto' },
  header:       { textAlign: 'center', marginBottom: 12 },
  badge:        { display: 'inline-block', background: '#1e293b', color: '#94a3b8', fontSize: 11, fontWeight: 700, letterSpacing: 2, padding: '4px 14px', borderRadius: 2, marginBottom: 8 },
  title:        { margin: '0 0 4px', fontSize: 32, fontWeight: 900, color: '#0f172a', letterSpacing: -0.5 },
  subtitle:     { margin: 0, fontSize: 14, color: '#64748b' },
  section:      { marginBottom: 12 },
  label:        { display: 'block', fontSize: 10, fontWeight: 700, letterSpacing: 1.5, color: '#94a3b8', marginBottom: 7, textAlign: 'center' },
  pills:        { display: 'flex', flexWrap: 'wrap', gap: 6 },
  pill:         { padding: '7px 16px', borderRadius: 20, border: '1.5px solid #e2e8f0', background: '#fff', color: '#64748b', fontSize: 13, cursor: 'pointer' },
  filterBtn:    { padding: '9px 10px', borderRadius: 8, border: '1.5px solid #e2e8f0', background: '#fff', color: '#64748b', fontSize: 13, fontWeight: 600, cursor: 'pointer', textAlign: 'center', lineHeight: 1.3 },
  filterRow:    { display: 'flex', gap: 6 },
  pillActive:   { background: '#1e293b', color: '#fff', border: '1.5px solid #1e293b' },
  countRow:     { display: 'flex', gap: 8 },
  countBtn:     { padding: '0 14px', height: 44, minWidth: 44, borderRadius: 8, border: '1.5px solid #e2e8f0', background: '#fff', color: '#64748b', fontSize: 18, fontWeight: 700, cursor: 'pointer' },
  countBtnActive: { background: '#1e293b', color: '#fff', border: '1.5px solid #1e293b' },
  topicsGrid:   { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 10, marginBottom: 12 },
  topicCard:    { background: '#fff', borderRadius: 10, padding: '12px 14px', boxShadow: '0 1px 3px rgba(0,0,0,0.06)' },
  topicItem:    { fontSize: 12, color: '#64748b', marginTop: 4, lineHeight: 1.4 },
  error:        { background: '#fee2e2', color: '#991b1b', padding: '10px 14px', borderRadius: 8, fontSize: 14, marginBottom: 12 },
  startBtn:     { display: 'block', width: '100%', padding: '16px', background: '#1e293b', color: '#fff', border: 'none', borderRadius: 12, fontSize: 18, fontWeight: 700, cursor: 'pointer', letterSpacing: 0.3, marginBottom: 6 },
  statsBar:     { display: 'flex', alignItems: 'center', gap: 4, marginBottom: 12, background: '#fff', borderRadius: 12, padding: '10px 14px', boxShadow: '0 1px 4px rgba(0,0,0,0.07)', border: 'none', cursor: 'pointer', width: '100%' },
  statsCell:    { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 2 },
  statsNum:     { fontSize: 18, fontWeight: 900, color: '#1e293b', fontFamily: 'monospace' },
  statsLbl:     { fontSize: 10, color: '#94a3b8', letterSpacing: 0.3, textTransform: 'uppercase' },
  statsArrow:   { fontSize: 12, color: '#94a3b8', marginLeft: 4 },
  modeRow:      { display: 'flex', gap: 8 },
  modeBtn:      { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, padding: '10px 8px', borderRadius: 10, border: '1.5px solid #e2e8f0', background: '#fff', cursor: 'pointer' },
  modeBtnActive:{ background: '#1e293b', border: '1.5px solid #1e293b', color: '#fff' },
  examBanner:   { background: '#fef3c7', border: '1px solid #f59e0b', borderRadius: 8, padding: '8px 12px', fontSize: 13, color: '#92400e', marginBottom: 10 },
  retryPoolBtn: { display: 'block', width: '100%', padding: '10px 14px', background: '#fef3c7', color: '#92400e', border: '1.5px solid #f59e0b', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', marginBottom: 8, textAlign: 'left' },
  bankStatus:   { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: '6px 0', fontSize: 12, color: '#94a3b8' },
  bankDot:      { width: 8, height: 8, borderRadius: '50%', display: 'inline-block' },
  darkToggle:   { position: 'fixed', top: 18, right: 22, zIndex: 1000, width: 48, height: 48, borderRadius: '50%', border: '1.5px solid #e2e8f0', background: '#fff', cursor: 'pointer', fontSize: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: '0 2px 10px rgba(0,0,0,0.12)', lineHeight: 1 },
  topBar:       { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 },
  backBtn:      { background: 'none', border: 'none', color: '#64748b', fontSize: 14, cursor: 'pointer', padding: '6px 0' },
  progWrap:     { flex: 1, display: 'flex', alignItems: 'center', gap: 8 },
  progTrack:    { flex: 1, height: 6, background: '#e2e8f0', borderRadius: 3, overflow: 'hidden' },
  progFill:     { height: '100%', background: '#6366f1', borderRadius: 3, transition: 'width 0.3s' },
  progText:     { fontSize: 12, color: '#94a3b8', whiteSpace: 'nowrap', fontFamily: 'monospace' },
  timerBadge:   { padding: '6px 13px', borderRadius: 6, color: '#fff', fontSize: 15, fontWeight: 700, fontFamily: 'monospace', letterSpacing: 1 },
  finishBtn:    { background: '#10b981', color: '#fff', border: 'none', padding: '8px 16px', borderRadius: 6, fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  qNav:         { display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
  qDot:         { width: 30, height: 30, borderRadius: 6, border: 'none', fontSize: 12, fontWeight: 700, cursor: 'pointer', fontFamily: 'monospace' },
  qCard:        { background: '#fff', borderRadius: 14, padding: '22px', boxShadow: '0 2px 8px rgba(0,0,0,0.07)', marginBottom: 14 },
  qMeta:        { display: 'flex', alignItems: 'center', gap: 6, marginBottom: 12, flexWrap: 'wrap' },
  chTag:        { fontSize: 12, fontWeight: 700, padding: '3px 9px', borderRadius: 4, fontFamily: 'monospace' },
  topicTag:     { fontSize: 11, fontWeight: 600, padding: '3px 9px', borderRadius: 4, background: '#f1f5f9', color: '#475569' },
  diffTag:      { fontSize: 12, fontWeight: 600, padding: '3px 9px', borderRadius: 4 },
  qNum:         { fontSize: 12, color: '#94a3b8', marginLeft: 'auto', fontFamily: 'monospace' },
  qText:        { fontSize: 17, color: '#1e293b', lineHeight: 1.65, margin: '0 0 16px', fontWeight: 500 },
  options:      { display: 'flex', flexDirection: 'column', gap: 10 },
  optBtn:       { display: 'flex', alignItems: 'flex-start', gap: 12, padding: '14px 16px', borderRadius: 10, cursor: 'pointer', fontSize: 15, lineHeight: 1.5, textAlign: 'left' },
  optLetter:    { fontWeight: 800, minWidth: 18, fontFamily: 'monospace', fontSize: 14, marginTop: 1 },
  checkmark:    { marginLeft: 'auto', fontWeight: 900, color: '#10b981' },
  cross:        { marginLeft: 'auto', fontWeight: 900, color: '#ef4444' },
  revealBtn:    { marginTop: 14, width: '100%', padding: '13px', background: '#1e293b', color: '#fff', border: 'none', borderRadius: 8, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
  explanation:  { marginTop: 14, background: '#f8fafc', border: '1px solid #e2e8f0', borderRadius: 8, padding: '14px 16px', fontSize: 14, color: '#475569', lineHeight: 1.6 },
  navRow:       { display: 'flex', justifyContent: 'space-between' },
  navBtn:       { background: '#fff', border: '1.5px solid #e2e8f0', color: '#1e293b', padding: '12px 24px', borderRadius: 8, fontSize: 15, fontWeight: 600, cursor: 'pointer' },
  resultsCard:  { background: '#fff', borderRadius: 14, padding: '28px 24px', boxShadow: '0 2px 12px rgba(0,0,0,0.08)' },
  breakdown:    { display: 'flex', flexDirection: 'column', gap: 12, margin: '18px 0' },
  bRow:         { display: 'flex', alignItems: 'center', gap: 10, fontSize: 14 },
  barWrap:      { flex: 1, height: 9, background: '#f1f5f9', borderRadius: 4, overflow: 'hidden' },
  bar:          { height: '100%', borderRadius: 4, transition: 'width 0.4s' },
  retryBtn:     { width: '100%', padding: '14px', background: '#fef3c7', color: '#92400e', border: '1.5px solid #f59e0b', borderRadius: 8, fontSize: 15, fontWeight: 700, cursor: 'pointer', marginBottom: 10 },
  resBtns:      { display: 'flex', gap: 8, marginTop: 10 },
  revBtn:       { flex: 1, padding: '13px', background: '#f1f5f9', color: '#1e293b', border: 'none', borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  homeBtn:      { flex: 1, padding: '13px', background: '#1e293b', color: '#fff', border: 'none', borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: 'pointer' },
  reviewCard:   { background: '#fff', borderRadius: 8, padding: '16px', marginBottom: 10, boxShadow: '0 1px 4px rgba(0,0,0,0.05)' },
  reviewOpt:    { padding: '8px 13px', borderRadius: 6, border: '1px solid #e2e8f0', fontSize: 13, color: '#475569', marginBottom: 4, background: '#f8fafc' },
  sumGrid:      { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))', gap: 10, marginBottom: 16 },
  sumCard:      { background: '#fff', borderRadius: 10, padding: '18px 12px', textAlign: 'center', boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
  secCard:      { background: '#fff', borderRadius: 12, padding: '22px', marginBottom: 14, boxShadow: '0 1px 4px rgba(0,0,0,0.06)' },
  secTitle:     { margin: '0 0 14px', fontSize: 16, fontWeight: 800, color: '#0f172a' },
  fcCard:       { borderRadius: 18, padding: '52px 32px 36px', minHeight: 240, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 16, transition: 'border-color 0.2s' },
  fcNo:         { flex: 1, padding: '14px', background: '#fee2e2', color: '#991b1b', border: '1.5px solid #ef4444', borderRadius: 8, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
  fcYes:        { flex: 1, padding: '14px', background: '#d1fae5', color: '#065f46', border: '1.5px solid #10b981', borderRadius: 8, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
}
